import { GoogleGenAI } from '@google/genai';
import { z } from 'zod';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

const CombinedQASchema = z.object({
  pass: z.boolean(),
  score: z.number().min(0).max(100),
  hasRandomText: z.boolean(),
  hasSketchesOrDrawings: z.boolean(),
  hasFundamentalError: z.boolean(),
  fundamentalErrorDescription: z.string().nullable(),
  productFidelity: z.string().transform((v) => {
    const valid = ['identical', 'minor_shift', 'altered', 'regenerated'] as const;
    if ((valid as readonly string[]).includes(v)) return v as typeof valid[number];
    if (v.includes('regenerat')) return 'regenerated' as const;
    if (v.includes('alter') || v.includes('significant')) return 'altered' as const;
    if (v.includes('minor') || v.includes('shift')) return 'minor_shift' as const;
    return 'altered' as const;
  }),
  productFidelityScore: z.number().min(0).max(35),
  sceneQuality: z.enum(['poor', 'acceptable', 'good', 'excellent']),
  physicallyPlausible: z.boolean(),
  humanAnatomy: z.enum(['no_person', 'natural', 'minor_issue', 'major_issue']),
  productIntegration: z.enum(['natural', 'awkward', 'impossible']),
  issues: z.array(z.string()),
});

export type CombinedQAResult = z.infer<typeof CombinedQASchema>;

// ---------------------------------------------------------------------------
// Prompt
// ---------------------------------------------------------------------------

const COMBINED_QA_PROMPT_WITH_FIDELITY = `You are a VERY strict product ad quality inspector. Your job is to ensure ZERO defective images reach customers. You are given TWO images:

**Image 1:** The ORIGINAL product photo (ground truth).
**Image 2:** The AI-generated advertisement.

Check Image 2 against Image 1 and score:

## 0. FUNDAMENTAL ERROR CHECK (INSTANT REJECTION — check this FIRST)
A fundamental error is anything that makes the image UNUSABLE for a customer. If ANY of these exist, hasFundamentalError = true and pass = false:
- Product is DISTORTED (melted, warped, wrong proportions vs original)
- Product is MISSING or barely visible
- Product is MERGED into another object or person's body
- Any person present has WRONG ANATOMY: extra/missing fingers, extra limbs, distorted face, uncanny valley expression, impossible body proportions
- Person holding product in physically impossible way
- Product appears TWICE or is duplicated unnaturally
- Image has major artifacts: half-rendered objects, glitch patterns, smeared regions
- Person has blurry/smeared face or clearly AI-generated "plastic" skin

## 1. RANDOM TEXT CHECK (auto-fail if found)
- Is there any random/generated text in the SCENE/BACKGROUND that is NOT on the product?
- Text that is PART OF THE PRODUCT is OK: keyboard keys, brand logos, product labels, screen content
- Generated text like "8K", "QUALITY", watermarks, gibberish = INSTANT FAIL
- EXCEPTION: The small "AI Generated by Clickkar" label at the bottom of the image is INTENTIONAL and NOT random text. IGNORE it completely.
- hasRandomText = true ONLY for scene/background text, not product text, and NOT for the Clickkar label

## 2. SKETCHES/DRAWINGS CHECK (auto-fail if found)
- Any line drawings, sketches, illustrations, or cartoon elements? = INSTANT FAIL

## 3. PRODUCT FIDELITY (0-35 points, MOST IMPORTANT)
- Does the product in Image 2 match the product in Image 1?
- 35: Identical — same shape, color, texture, brand text, logos
- 25: Minor shift — same product, slight color/texture change, brand text preserved
- 15: Altered — shape similar but material or color changed, OR brand text slightly different
- 5: Significantly altered — different shape/material/proportions
- 0: Regenerated — brand name/logo MISSING, CHANGED, or REPLACED

## 4. SCENE QUALITY (0-30 points)
- Is the scene photorealistic with proper lighting, shadows, reflections?
- Does the product look like it BELONGS in the scene (not pasted on)?
- Is the product the VISUAL FOCUS? It can dominate through SIZE (filling 40%+) OR through LIGHTING (brightest/sharpest element) OR through COMPOSITION (strategic placement with intentional negative space). All three are valid — the product just needs to be what your eye goes to first.
- SURFACE CONSISTENCY: Does the surface material maintain consistent texture, color, and grain? Deduct 5-10 points if surface abruptly changes near product edges.
- LIGHTING CONSISTENCY: Do shadows all fall in the same direction? Is the product lit from the same source as the scene?
- DYNAMIC ELEMENTS: If splashes, floating particles, or scattered elements are present, do they look physically plausible and add to the composition? Bonus points for compelling dynamic elements.

## 5. PHYSICAL PLAUSIBILITY (0-15 points)
- Product sitting naturally ON a flat surface or held naturally by a person?
- Not embedded inside another object?
- No floating or defying gravity?

## 6. AD READINESS (0-20 points)
- Would a real brand use this for Instagram/advertising?
- No distracting artifacts?
- Professional composition?

## 7. HUMAN ANATOMY (if a person is present)
- "no_person": No human in the image
- "natural": Person looks completely real and natural
- "minor_issue": Slight imperfections but still usable (slightly odd finger position, etc.)
- "major_issue": Obvious AI artifacts on person — INSTANT FAIL

## 8. PRODUCT INTEGRATION
- "natural": Product looks like it naturally belongs (held properly, sitting on surface correctly)
- "awkward": Product placement looks slightly off but still usable
- "impossible": Product is floating, merged into person, or physically impossible — INSTANT FAIL

**Total score: fidelity(0-35) + scene(0-30) + plausibility(0-15) + readiness(0-20) = 0-100**
**Pass: score >= 65 AND productFidelityScore >= 25 AND no random text AND no sketches AND no fundamental errors AND humanAnatomy != "major_issue" AND productIntegration != "impossible"**

Return valid JSON only:
{
  "pass": boolean,
  "score": number,
  "hasRandomText": boolean,
  "hasSketchesOrDrawings": boolean,
  "hasFundamentalError": boolean,
  "fundamentalErrorDescription": string | null,
  "productFidelity": "identical" | "minor_shift" | "altered" | "regenerated",
  "productFidelityScore": number,
  "sceneQuality": "poor" | "acceptable" | "good" | "excellent",
  "physicallyPlausible": boolean,
  "humanAnatomy": "no_person" | "natural" | "minor_issue" | "major_issue",
  "productIntegration": "natural" | "awkward" | "impossible",
  "issues": string[]
}`;

const COMBINED_QA_PROMPT_NO_FIDELITY = `You are a VERY strict product ad quality inspector. Your job is to ensure ZERO defective images reach customers. Check this AI-generated advertisement image:

## 0. FUNDAMENTAL ERROR CHECK (INSTANT REJECTION — check this FIRST)
A fundamental error is anything that makes the image UNUSABLE for a customer. If ANY of these exist, hasFundamentalError = true and pass = false:
- Product is DISTORTED (melted, warped, wrong proportions)
- Product is MISSING or barely visible
- Product is MERGED into another object or person's body
- Any person present has WRONG ANATOMY: extra/missing fingers, extra limbs, distorted face, uncanny valley expression, impossible body proportions, teeth that look wrong
- Person holding product in physically impossible way (hand going through product, wrong grip)
- Product appears TWICE or is duplicated unnaturally
- Image has major artifacts: half-rendered objects, glitch patterns, smeared regions
- Person has blurry/smeared face or clearly AI-generated "plastic" skin
- Person's hand has wrong number of fingers (count them carefully — must be exactly 5 per hand)

## 1. RANDOM TEXT CHECK (auto-fail if found)
- Any random/generated text in the SCENE/BACKGROUND? (product text is OK)
- "8K", "QUALITY", watermarks, gibberish = INSTANT FAIL
- EXCEPTION: The small "AI Generated by Clickkar" label at the bottom of the image is INTENTIONAL and NOT random text. IGNORE it completely.

## 2. SKETCHES/DRAWINGS CHECK (auto-fail if found)
- Any line drawings, sketches, illustrations, or cartoon elements?

## 3. SCENE QUALITY (0-40 points)
- Photorealistic with proper lighting, shadows, reflections?
- Product is clearly visible and the VISUAL FOCUS (through size, lighting, sharpness, or strategic placement)?
- Professional composition with intentional dynamic elements (splashes, particles, scattered ingredients)?
- Bonus for compelling creative direction — does this look like a scroll-stopping AD, not just a product photo?

## 4. PHYSICAL PLAUSIBILITY (0-20 points)
- Product held naturally / sitting on surface naturally?
- No floating or defying physics?
- No impossible interactions?

## 5. HUMAN QUALITY (0-20 points, if person present; skip if no person → give 20)
- Person looks completely photorealistic? (not AI-generated looking)
- Natural skin texture, realistic eyes, natural expression?
- Hands look correct? (right number of fingers, natural grip)
- Person's clothing looks real and natural?
- 20: Looks like a real photo of a real person
- 10: Minor imperfections but still believable
- 0: Obviously AI-generated person, uncanny valley, anatomy issues

## 6. AD READINESS (0-20 points)
- Would a brand use this for Instagram?
- Professional quality, no artifacts?

**Total: scene(0-40) + plausibility(0-20) + human(0-20) + readiness(0-20) = 0-100**
**Pass: score >= 65 AND no random text AND no sketches AND no fundamental errors AND humanAnatomy != "major_issue" AND productIntegration != "impossible"**

## 7. HUMAN ANATOMY (if a person is present)
- "no_person": No human in the image
- "natural": Person looks completely real and natural
- "minor_issue": Slight imperfections but still usable
- "major_issue": Obvious AI artifacts on person — extra fingers, distorted face, impossible anatomy

## 8. PRODUCT INTEGRATION
- "natural": Product looks like it naturally belongs
- "awkward": Product placement looks slightly off but still usable
- "impossible": Product is floating, merged into person, or physically impossible

Return valid JSON only:
{
  "pass": boolean,
  "score": number,
  "hasRandomText": boolean,
  "hasSketchesOrDrawings": boolean,
  "hasFundamentalError": boolean,
  "fundamentalErrorDescription": string | null,
  "productFidelity": "identical",
  "productFidelityScore": 35,
  "sceneQuality": "poor" | "acceptable" | "good" | "excellent",
  "physicallyPlausible": boolean,
  "humanAnatomy": "no_person" | "natural" | "minor_issue" | "major_issue",
  "productIntegration": "natural" | "awkward" | "impossible",
  "issues": string[]
}`;

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

function detectMime(buf: Buffer): 'image/jpeg' | 'image/png' | 'image/webp' {
  if (buf[0] === 0x89 && buf[1] === 0x50) return 'image/png';
  if (buf[0] === 0x52 && buf[1] === 0x49) return 'image/webp';
  return 'image/jpeg';
}

/**
 * Single combined QA check — replaces separate supervisor + comparative QA.
 * One Gemini call instead of two.
 *
 * @param checkFidelity - true for Track A (branded), false for Track B (unbranded)
 */
export async function combinedQualityCheck(
  inputBuffer: Buffer,
  outputBuffer: Buffer,
  options: { checkFidelity: boolean }
): Promise<CombinedQAResult> {
  const startMs = Date.now();

  const genai = new GoogleGenAI({
    apiKey: process.env['GOOGLE_AI_API_KEY'] ?? process.env['GOOGLE_GENAI_API_KEY'] ?? '',
  });

  const outputBase64 = outputBuffer.toString('base64');
  const outputMime = detectMime(outputBuffer);

  const parts: Array<{ inlineData?: { mimeType: string; data: string }; text?: string }> = [];

  if (options.checkFidelity) {
    // Send both images for fidelity comparison
    const inputBase64 = inputBuffer.toString('base64');
    const inputMime = detectMime(inputBuffer);
    parts.push({ inlineData: { mimeType: inputMime, data: inputBase64 } });
    parts.push({ inlineData: { mimeType: outputMime, data: outputBase64 } });
    parts.push({ text: COMBINED_QA_PROMPT_WITH_FIDELITY });
  } else {
    // Only send the output for scene quality check
    parts.push({ inlineData: { mimeType: outputMime, data: outputBase64 } });
    parts.push({ text: COMBINED_QA_PROMPT_NO_FIDELITY });
  }

  try {
    const timeoutPromise = new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error('combinedQualityCheck timed out after 30s')), 30_000)
    );
    const response = await Promise.race([
      genai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: [{ role: 'user', parts }],
      }),
      timeoutPromise,
    ]);

    const rawText = response.candidates?.[0]?.content?.parts?.[0]?.text ?? '';
    const cleaned = rawText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();
    const parsed = JSON.parse(cleaned);
    const result = CombinedQASchema.safeParse(parsed);

    if (!result.success) {
      throw new Error(`Combined QA schema failed: ${result.error.message}`);
    }

    console.info(JSON.stringify({
      event: 'combined_qa_complete',
      pass: result.data.pass,
      score: result.data.score,
      fidelity: result.data.productFidelity,
      fidelityScore: result.data.productFidelityScore,
      hasRandomText: result.data.hasRandomText,
      issues: result.data.issues,
      durationMs: Date.now() - startMs,
    }));

    return result.data;
  } catch (err) {
    const isTimeout = err instanceof Error && err.message.includes('timed out');
    if (isTimeout) {
      console.warn(JSON.stringify({
        event: 'combined_qa_timeout',
        error: err.message,
        durationMs: Date.now() - startMs,
      }));
    } else {
      console.error(JSON.stringify({
        event: 'combined_qa_error',
        error: err instanceof Error ? err.message : String(err),
        durationMs: Date.now() - startMs,
      }));
    }

    // Fail conservative — assume bad quality so we try fallback
    return {
      pass: false,
      score: 40,
      hasRandomText: false,
      hasSketchesOrDrawings: false,
      hasFundamentalError: false,
      fundamentalErrorDescription: null,
      productFidelity: 'altered',
      productFidelityScore: 10,
      sceneQuality: 'acceptable',
      physicallyPlausible: true,
      humanAnatomy: 'no_person',
      productIntegration: 'natural',
      issues: ['QA check failed — defaulting to conservative score'],
    };
  }
}
